[tool.poetry]
name = "workout-coach-api"
version = "2.0.0"
description = "AI Calisthenics Coach API"
authors = ["Michaud Moise"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"
uvicorn = "*"
google-genai = "2.4.0"
gspread = "*"
google-auth = "*"
python-dotenv = "*"
plotly = "*"
pandas = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
